Rename: Rename Upload Text to Upload to Pastebin
diced/zipline pull request #381
Opened 2023-04-19 22:51 UTC by er9ugi9uier9

I accidentally deleted the fork repo not knowing it will delete the pull request lol.

Old one: https://github.com/diced/zipline/pull/378

2023-04-19 22:56 UTC, diced commented
I'm unsure if this would be a good idea as it could be confused with the website, https://pastebin.com. I would be open to any other naming suggestions though.

2023-04-20 23:01 UTC, xSkeletor commented
I agree with @diced, I think pastebin is not a good naming idea since it is directly connected to another website/service. Instead, I think leaving the current upload text format is fine and makes sense.

2023-04-25 00:13 UTC, TacticalTechJay requested changes

2023-04-25 00:13 UTC, TacticalTechJay commented on src/components/pages/Upload/Text.tsx
> +    options.format !== 'random' && req.setRequestHeader('Format', options.format);
Irrelevant change. This does not seem to match with your PR's title.

2023-04-29 03:34 UTC, diced commented
I will be closing this as I see the change being pretty useless, and seems like the source within the PR does not have anything to do with the PR's title.

2023-04-29 03:34 UTC, closed without merging